# Generated by Django 4.1 on 2022-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Founded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=500)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post", name="moto", field=models.CharField(max_length=300),
        ),
    ]
