# Generated by Django 4.1 on 2022-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0002_company_founded_project_alter_post_moto"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
