# Generated by Django 4.1 on 2022-08-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0003_project_number"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Member",),
    ]
