# Generated by Django 4.1 on 2022-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0004_alter_recruit_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
