# Generated by Django 4.1 on 2022-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0005_recruit_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="recruit", name="pub_date",),
        migrations.RemoveField(model_name="recruit", name="status",),
        migrations.AddField(
            model_name="recruit",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruit",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
