# Generated by Django 4.0.4 on 2022-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0007_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='job',
        ),
        migrations.AlterField(
            model_name='member',
            name='moto',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
