# Generated by Django 4.0.4 on 2022-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0008_remove_member_job_alter_member_moto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='moto',
            field=models.CharField(max_length=20),
        ),
    ]
