# Generated by Django 4.0.4 on 2022-08-21 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0009_alter_member_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
