# Generated by Django 4.1 on 2022-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likelionyonsei_app", "0010_alter_recruit_end_date_alter_recruit_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="title",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
