# Generated by Django 4.1 on 2022-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0011_recruit_title_alter_recruit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
