# Generated by Django 4.0.4 on 2022-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0012_member_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '대표'), (1, '부대표'), (2, '운영진'), (3, '일반 구성원')], default=3),
        ),
    ]
