# Generated by Django 4.1 on 2022-09-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likelionyonsei_app', '0017_project_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Founded',
        ),
    ]
